version: '3'
services:
  redis_server:
    build:
      context: ./redis_server/
    container_name: redis
    depends_on:
      - web_server
      - cache_server
      - database_server
    volumes:
      - ./redis_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "6379:6379"
    networks:
      - internal

  cache_server:
    build:
      context: ./cache_server/
    container_name: varnish
    depends_on:
      - web_server
    volumes:
      - ./cache_server/default.vcl:/etc/varnish/default.vcl
      - ./cache_server/varnish:/etc/default/varnish
      - ./cache_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    ports:
      - "6081:6081"
      - "6082:6082"
    networks:
      - internal
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      
  web_server:
    build:
      context: ./web_server/
    container_name: apache2
    volumes:
      - ./magento2:/var/www/html  
      - ./web_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    labels:
      - traefik-backend=web_server
      - traefik.enable=true
      - traefik.frontend.rule=Host:store.domain.com #custom domain 
      - traefik.port=8080
      - traefik.docker.network=web
    networks:
      - web
      - internal
    
  database_server:
    build:
      context: ./database_server/
      args:
        - mysql_password=aadyantha_mysql_ravi
        - mysql_database=aadyantha_mysql_ravi
    container_name: mysql
    volumes: 
      - ./database_server/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./database_server/mysql.sh:/etc/mysql.sh
    ports:
      - "3306:3306"
    networks:
      - internal
networks:
   web:
     external: true
   internal:
    external: false

